import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "Xenith terms of service. Understand the terms and conditions for using the Xenith translation and file conversion service.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsOfServicePage() {
  return (
    <div className="mx-auto max-w-3xl px-4 py-16 sm:px-6 lg:px-8">
      <h1 className="text-3xl font-bold tracking-tight">Terms of Service</h1>
      <p className="mt-2 text-sm text-muted-foreground">
        Last updated: March 12, 2026
      </p>

      {/* English Section */}
      <section className="mt-10 space-y-6">
        <h2 className="text-xl font-semibold">English</h2>

        <div className="space-y-4 text-muted-foreground leading-relaxed">
          <h3 className="text-lg font-medium text-foreground">
            Acceptance of Terms
          </h3>
          <p>
            By using Xenith, you agree to these Terms of Service. If you do not
            agree, please do not use the service.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            Service Description
          </h3>
          <p>
            Xenith is a free online tool for translating text and files, and
            converting between document formats including HWPX, PDF, DOCX, and
            images (OCR). The service is provided &ldquo;as is&rdquo; and free
            of charge.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            No Warranty on Translation Accuracy
          </h3>
          <p>
            Translations are generated by AI and may contain errors,
            inaccuracies, or omissions. Xenith makes no guarantees regarding the
            accuracy, completeness, or reliability of any translation output.{" "}
            <strong>
              Users are solely responsible for verifying translations before
              using them for legal, official, medical, or any other
              critical purpose.
            </strong>
          </p>

          <h3 className="text-lg font-medium text-foreground">
            File Size Limits
          </h3>
          <p>
            The maximum file size for uploads is <strong>20 MB</strong>. Files
            exceeding this limit will be rejected.
          </p>

          <h3 className="text-lg font-medium text-foreground">Rate Limits</h3>
          <p>
            To ensure fair access for all users, rate limits apply. Excessive or
            automated usage may result in temporary restrictions. We reserve the
            right to throttle or block traffic that negatively impacts service
            availability.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            Acceptable Use
          </h3>
          <p>
            You agree not to use Xenith for any unlawful purpose, to upload
            malicious files, or to attempt to disrupt the service. You retain
            ownership of all content you upload; we claim no rights over your
            files or translations.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            Limitation of Liability
          </h3>
          <p>
            Xenith is provided without any express or implied warranties. In no
            event shall Xenith or its maintainers be liable for any damages
            arising from the use or inability to use the service, including but
            not limited to damages from inaccurate translations, data loss, or
            service interruptions.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            Changes to Terms
          </h3>
          <p>
            We may update these terms from time to time. Continued use of Xenith
            after changes constitutes acceptance of the updated terms.
          </p>

          <h3 className="text-lg font-medium text-foreground">Contact</h3>
          <p>
            Questions about these terms? Please reach out via{" "}
            <a
              href="https://github.com/yusikkim/xenith/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-foreground"
            >
              GitHub Issues
            </a>
            .
          </p>
        </div>
      </section>

      {/* Korean Section */}
      <section className="mt-16 space-y-6">
        <h2 className="text-xl font-semibold">한국어 (Korean)</h2>

        <div className="space-y-4 text-muted-foreground leading-relaxed">
          <h3 className="text-lg font-medium text-foreground">
            이용약관 동의
          </h3>
          <p>
            Xenith를 사용함으로써 본 이용약관에 동의하는 것으로 간주됩니다.
            동의하지 않으시면 서비스를 이용하지 마시기 바랍니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            서비스 설명
          </h3>
          <p>
            Xenith는 텍스트와 파일을 번역하고, HWPX, PDF, DOCX, 이미지(OCR)
            등 문서 형식 간 변환을 제공하는 무료 온라인 도구입니다. 서비스는
            &ldquo;있는 그대로(as is)&rdquo; 무료로 제공됩니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            번역 정확성 보증 불가
          </h3>
          <p>
            번역은 AI에 의해 생성되며, 오류, 부정확성 또는 누락이 포함될 수
            있습니다. Xenith는 번역 결과의 정확성, 완전성 또는 신뢰성에 대해
            어떠한 보증도 하지 않습니다.{" "}
            <strong>
              법률, 공식, 의료 또는 기타 중요한 목적으로 번역을 사용하기 전에
              반드시 직접 검증하시기 바랍니다.
            </strong>
          </p>

          <h3 className="text-lg font-medium text-foreground">
            파일 크기 제한
          </h3>
          <p>
            업로드 가능한 최대 파일 크기는 <strong>20 MB</strong>입니다. 이
            제한을 초과하는 파일은 거부됩니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            이용 제한 (Rate Limits)
          </h3>
          <p>
            모든 사용자에게 공정한 접근을 보장하기 위해 이용 제한이
            적용됩니다. 과도한 사용이나 자동화된 사용은 일시적인 제한을 받을
            수 있습니다. 서비스 가용성에 부정적인 영향을 미치는 트래픽을
            제한하거나 차단할 권리를 보유합니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            허용되는 사용
          </h3>
          <p>
            불법적인 목적으로 Xenith를 사용하거나, 악성 파일을 업로드하거나,
            서비스를 방해하는 행위를 하지 않는 것에 동의합니다. 업로드한 모든
            콘텐츠의 소유권은 사용자에게 있으며, 파일이나 번역에 대한 어떠한
            권리도 주장하지 않습니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            책임 제한
          </h3>
          <p>
            Xenith는 명시적이거나 묵시적인 보증 없이 제공됩니다. 부정확한
            번역, 데이터 손실 또는 서비스 중단 등 서비스 사용 또는 사용
            불능으로 발생하는 어떠한 손해에 대해서도 Xenith 또는 관리자는
            책임을 지지 않습니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">
            약관 변경
          </h3>
          <p>
            이 약관은 수시로 업데이트될 수 있습니다. 변경 후 Xenith를 계속
            사용하면 업데이트된 약관에 동의하는 것으로 간주됩니다.
          </p>

          <h3 className="text-lg font-medium text-foreground">문의</h3>
          <p>
            이 약관에 대한 질문이 있으시면{" "}
            <a
              href="https://github.com/yusikkim/xenith/issues"
              target="_blank"
              rel="noopener noreferrer"
              className="underline hover:text-foreground"
            >
              GitHub Issues
            </a>
            를 통해 연락해 주세요.
          </p>
        </div>
      </section>
    </div>
  );
}
